CREATE DATABASE QUALIDADE;

use QUALIDADE;

CREATE TABLE INFO_MATERIAL(
    OP INT not null PRIMARY KEY,
    CLIENTE INT not null,
    TIPO_INSP VARCHAR (20) not null,
    PEDIDO INT not null,
    QUANT INT not null,
    DATA_ENTREGA DATE not null,
    SNQC BIT null );
    
    
CREATE TABLE STATUS(
    OP INT NOT NULL,
    SNQC VARCHAR (20) null,
    RELATORIO_DIM VARCHAR(20) NOT NULL,
    CALIBRACAO VARCHAR (20) not null,
    VISUAL VARCHAR (20) not null,
    QUANT_APROVADA INT null,
    SOBRA INT NULL,
    LOCAL VARCHAR(20) NOT NULL,
    
    FOREIGN KEY (OP) REFERENCES info_material(OP));